import { Head, Appear, Image, withDeck } from 'mdx-deck'  // https://github.com/jxnblk/mdx-deck
import { CodeSurfer } from "mdx-deck-code-surfer"
import { FullScreenCode } from "mdx-deck/layouts";
import nightOwl from "prism-react-renderer/themes/nightOwl"
import ReplIt from "../../components/replit";

## Promise Error Handling 

* doSomethingAsync().then(onSuccess,onError)
* the `onError` will catch errors in `doSomethingAsync` not in `onSuccess`

---

## Promise Error Handling

```javascript
getData().then(function onSuccess() {
    // executes if getData resolves
 }, function onError(errors) { 
     // executes if getData rejects, or throws an error
 })
```

---

## How Do Handle an Error If Something Breaks in `onSuccess`?

```javascript
getData().then(function onSuccess() {
    // executes if getData resolves
 }).then(null, function onError(error) {
     // if something fails in getData,
     // or onSuccess - then it will be captured here
 })
```
---

<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-1.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Promise Errors"
  showNumbers
  steps={[
    { notes: "Lets look at how errors flow through" },
    { lines: [2], notes: "Handles success or error of getData" },
    {
      tokens: {
        3: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        2: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      },
      notes: "Handles error from the then above"
    },
    {
      tokens: {
        4: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        3: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
      },
      notes: "Handles error from the successB above"
    },
    {
      tokens: {
        2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       
      },
      notes: "If this resolves"
    },
    {
      tokens: { 
          2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
          3: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13] },
      notes: "successB gets the value"
    },
    {
      tokens: {
        2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       
      },
      notes: "If this rejects or throws"
    },
    {
      tokens: { 
          2: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
          3: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24]},
      notes: "successAError gets called"
    },
    { notes: "This is generally not a good pattern" }
  ]}
/>

---

# What Do We Do Then?

---
<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-2.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Single Error Handler"
  showNumbers
  steps={[
    { notes: "Let errors fall through" },
    { lines: [5], notes: "Gets any errors that happen above" },
  ]}
/>

---

<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-3.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Catch and Release"
  showNumbers
  steps={[
    { notes: "Let errors fall through" },
    { range: [5,8], notes: "Catch and Release" },
    { lines: [6], notes: "Can do localized error handling" },
    { lines: [7], notes: "Pass it onto consumers if needed" },
    {}
  ]}
/>

---
### When would you want to handle other than at the end?

#### If you have a fall-back value that can continue the chain

---
<CodeSurfer
  code={require("!raw-loader!./snippets/promise-errors-4.snippet")}
  theme={nightOwl}
  lang="javascript"
  title="Graceful Errors"
  showNumbers
  steps={[
    { notes: "If you can gracefully recover" },
    { lines: [3], notes: "Could return a cached value" },
    { range: [5,6], notes: "And continue the chain with the value" },
    {}
  ]}
/>

---
export default FullScreenCode

## Exploring Errors

<ReplIt src="https://repl.it/@e_schultz/Promise-Error-Handling-start?lite=true"/>